<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.util.List,java.util.Collections,java.net.URLEncoder,java.nio.charset.StandardCharsets,br.com.saborearte.model.Log" %>
<%!
private String h(Object v){if(v==null)return "";return String.valueOf(v).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
private String enc(Object v){return URLEncoder.encode(v==null?"":String.valueOf(v),StandardCharsets.UTF_8);}
%>
<%
String ctx=request.getContextPath();
List<Log> logs=(List<Log>)request.getAttribute("logs");if(logs==null)logs=Collections.emptyList();
List<Log> exportLogs=(List<Log>)request.getAttribute("logsExportacao");if(exportLogs==null)exportLogs=Collections.emptyList();
int pageAtual=request.getAttribute("page")instanceof Integer?(Integer)request.getAttribute("page"):1;
int size=request.getAttribute("size")instanceof Integer?(Integer)request.getAttribute("size"):20;
int totalPages=request.getAttribute("totalPages")instanceof Integer?(Integer)request.getAttribute("totalPages"):1;
int total=request.getAttribute("totalLogs")instanceof Integer?(Integer)request.getAttribute("totalLogs"):0;
String busca=h(request.getAttribute("busca")),acao=h(request.getAttribute("acaoLog")),entidade=h(request.getAttribute("entidade")),periodo=h(request.getAttribute("periodo"));
String dataInicio=h(request.getAttribute("dataInicio")),dataFim=h(request.getAttribute("dataFim")),exportTipo=h(request.getAttribute("exportTipo")),erro=h(request.getAttribute("erro"));
String filtros="&size="+size+"&busca="+enc(request.getAttribute("busca"))+"&acaoLog="+enc(request.getAttribute("acaoLog"))+"&entidade="+enc(request.getAttribute("entidade"))+"&periodo="+enc(request.getAttribute("periodo"))+"&dataInicio="+enc(request.getAttribute("dataInicio"))+"&dataFim="+enc(request.getAttribute("dataFim"));
%>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Auditoria</title>
<style>
body{margin:0;background:#f7f3eb;color:#263523;font:14px Arial,sans-serif}.page{margin-left:250px;padding:30px}.card{background:#fff;border:1px solid #ddd3c2;border-radius:8px;margin-bottom:18px}.head{padding:18px 22px;border-bottom:1px solid #e7dfd2}h1{font-family:Georgia,serif;margin:0 0 6px}.filters{display:grid;grid-template-columns:2fr repeat(5,1fr);gap:12px;padding:18px}.filters label{font-size:11px;text-transform:uppercase;letter-spacing:.08em}.filters input,.filters select{box-sizing:border-box;width:100%;padding:10px;border:1px solid #d9cfbf;border-radius:4px;background:#faf8f3}.actions{display:flex;gap:8px;padding:0 18px 18px}.btn{padding:10px 14px;border:1px solid #576b43;border-radius:4px;background:#576b43;color:white;text-decoration:none;cursor:pointer}.btn.alt{background:white;color:#425332}.error{margin:15px;padding:12px;background:#fee;color:#922}table{border-collapse:collapse;width:100%}th,td{padding:12px;border-bottom:1px solid #ece5d9;text-align:left}th{font-size:11px;text-transform:uppercase;background:#faf8f3}.footer{display:flex;justify-content:space-between;padding:16px}.pagination a,.pagination span{padding:7px 10px;text-decoration:none}.pagination .active{background:#576b43;color:#fff}.empty{text-align:center;padding:45px;color:#7b806f}.export-table{display:none}@media(max-width:1000px){.page{margin-left:0}.filters{grid-template-columns:1fr 1fr}}@media print{.sidebar,.filters-card,.screen-table,.footer,.actions{display:none!important}.page{margin:0}.export-table{display:table}}
</style></head><body><%@ include file="includes/sidebar.jsp" %><main class="page"><div class="head"><h1>Log de Auditoria</h1><span>Consulta administrativa, paginada e somente leitura</span></div>
<%if(!erro.isEmpty()){%><div class="error"><%=erro%></div><%}%>
<section class="card filters-card"><form method="get" action="<%=ctx%>/LogController"><div class="filters">
<label>Pesquisar<input name="busca" maxlength="100" value="<%=busca%>" placeholder="Usuário ou descrição"></label>
<label>Ação<select name="acaoLog"><option value="">Todas</option><%String[] as={"CRIAR_RASCUNHO","ENVIAR_REVISAO","APROVAR_RECEITA","REJEITAR_RECEITA","ALTERAR_ATIVIDADE","COMENTAR","RESPONDER_COMENTARIO","MODERAR_COMENTARIO","LOGIN"};for(String a:as){%><option value="<%=a%>" <%=a.equals(acao)?"selected":""%>><%=a%></option><%}%></select></label>
<label>Entidade<select name="entidade"><option value="">Todas</option><%String[] es={"RECEITA","COMENTARIO","USUARIO","RELATORIO","SESSAO"};for(String e:es){%><option value="<%=e%>" <%=e.equals(entidade)?"selected":""%>><%=e%></option><%}%></select></label>
<label>Período<select name="periodo"><option value="">Todos</option><option value="hoje" <%="hoje".equals(periodo)?"selected":""%>>Hoje</option><option value="7dias" <%="7dias".equals(periodo)?"selected":""%>>7 dias</option><option value="30dias" <%="30dias".equals(periodo)?"selected":""%>>30 dias</option><option value="personalizado" <%="personalizado".equals(periodo)?"selected":""%>>Personalizado</option></select></label>
<label>Início<input type="date" name="dataInicio" value="<%=dataInicio%>"></label><label>Fim<input type="date" name="dataFim" value="<%=dataFim%>"></label></div>
<div class="actions"><button class="btn" type="submit">Aplicar filtros</button><a class="btn alt" href="<%=ctx%>/LogController">Limpar</a></div></form></section>
<section class="card"><div class="actions" style="padding-top:18px"><a class="btn alt" href="<%=ctx%>/LogController?export=pdf<%=filtros%>">Exportar PDF</a><a class="btn alt" href="<%=ctx%>/LogController?export=excel<%=filtros%>">Exportar Excel</a><a class="btn alt" href="<%=ctx%>/LogController?export=print<%=filtros%>">Imprimir</a></div>
<table class="screen-table"><thead><tr><th>Data</th><th>Usuário</th><th>Perfil</th><th>Ação</th><th>Entidade</th><th>Descrição</th></tr></thead><tbody><%if(logs.isEmpty()){%><tr><td class="empty" colspan="6">Nenhum registro encontrado</td></tr><%}else for(Log l:logs){%><tr><td><%=h(l.getData_log())%></td><td><%=h(l.getNome_usuario())%></td><td><%=h(l.getTipo_usuario())%></td><td><%=h(l.getAcao_log())%></td><td><%=h(l.getEntidade_log())%></td><td><%=h(l.getDetalhe_log())%></td></tr><%}%></tbody></table>
<div class="footer"><span><%=total%> registro(s)</span><nav class="pagination"><%if(pageAtual>1){%><a href="<%=ctx%>/LogController?page=<%=pageAtual-1%><%=filtros%>">‹</a><%}int pi=Math.max(1,pageAtual-2),pf=Math.min(totalPages,pageAtual+2);if(pi>1){%><a href="<%=ctx%>/LogController?page=1<%=filtros%>">1</a><span>…</span><%}for(int p=pi;p<=pf;p++){if(p==pageAtual){%><span class="active"><%=p%></span><%}else{%><a href="<%=ctx%>/LogController?page=<%=p%><%=filtros%>"><%=p%></a><%}}if(pf<totalPages){%><span>…</span><a href="<%=ctx%>/LogController?page=<%=totalPages%><%=filtros%>"><%=totalPages%></a><%}if(pageAtual<totalPages){%><a href="<%=ctx%>/LogController?page=<%=pageAtual+1%><%=filtros%>">›</a><%}%></nav></div></section>
<table id="exportData" class="export-table"><thead><tr><th>Data</th><th>Usuário</th><th>Perfil</th><th>Ação</th><th>Entidade</th><th>Descrição</th></tr></thead><tbody><%for(Log l:exportLogs){%><tr><td><%=h(l.getData_log())%></td><td><%=h(l.getNome_usuario())%></td><td><%=h(l.getTipo_usuario())%></td><td><%=h(l.getAcao_log())%></td><td><%=h(l.getEntidade_log())%></td><td><%=h(l.getDetalhe_log())%></td></tr><%}%></tbody></table></main>
<script>
const exportType='<%=exportTipo%>';if(exportType==='print')window.print();
if(exportType==='excel'){const safe=v=>/^[=+\-@]/.test(v)?"'"+v:v;const rows=[...document.querySelectorAll('#exportData tr')].map(r=>[...r.cells].map(c=>'"'+safe(c.innerText).replaceAll('"','""')+'"').join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+rows],{type:'text/csv'}));a.download='auditoria.csv';a.click();}
if(exportType==='pdf')window.print();
</script></body></html>
