<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.util.List,java.util.Collections" %>
<%@ page import="br.com.saborearte.dao.RelatorioDAO.ReceitaRelatorio" %>
<%@ page import="br.com.saborearte.dao.RelatorioDAO.ComentarioRelatorio" %>
<%@ page import="br.com.saborearte.dao.RelatorioDAO.CategoriaRelatorio" %>
<%!
private String h(Object v){if(v==null)return "";return String.valueOf(v).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
private String label(Object v){if(v==null)return "";String s=String.valueOf(v).toLowerCase().replace('_',' ');return s.isEmpty()?s:Character.toUpperCase(s.charAt(0))+s.substring(1);}
%>
<%
request.setAttribute("currentPage","relatorios");String ctx=request.getContextPath();String perfil=request.getAttribute("perfilRelatorio")==null?"editor":String.valueOf(request.getAttribute("perfilRelatorio"));
String rota="autor".equals(perfil)?"/relatorio-autor":"/relatorio-editor";String tipo=request.getAttribute("tipoRelatorio")==null?"receitas":String.valueOf(request.getAttribute("tipoRelatorio"));
Integer categoria=(Integer)request.getAttribute("categoriaFiltro");String autor=request.getAttribute("autorFiltro")==null?"":String.valueOf(request.getAttribute("autorFiltro"));String status=request.getAttribute("statusFiltro")==null?"":String.valueOf(request.getAttribute("statusFiltro"));
Object di=request.getAttribute("dataInicio"),df=request.getAttribute("dataFim");
List<ReceitaRelatorio> receitas=(List<ReceitaRelatorio>)request.getAttribute("receitas");if(receitas==null)receitas=Collections.emptyList();
List<ComentarioRelatorio> comentarios=(List<ComentarioRelatorio>)request.getAttribute("comentarios");if(comentarios==null)comentarios=Collections.emptyList();
List<CategoriaRelatorio> categorias=(List<CategoriaRelatorio>)request.getAttribute("categoriasFiltro");if(categorias==null)categorias=Collections.emptyList();
int total="receitas".equals(tipo)?receitas.size():comentarios.size();
%>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sabor &amp; Arte — Relatórios</title>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&amp;family=Nunito:wght@700;800&amp;family=Playfair+Display:ital,wght@0,600;1,600&amp;display=swap" rel="stylesheet"><script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.29/jspdf.plugin.autotable.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script>
<style>
:root{--moss:#4a5e3a;--cream:#f3efe6;--cream-dark:#e5dccb;--warm:#fffdf8;--text:#293022;--mid:#596052;--light:#899080;--gold:#c4a265;--danger:#a64b47}*{box-sizing:border-box}body{margin:0;background:var(--cream);color:var(--text);font-family:'DM Sans',sans-serif}.main{margin-left:240px;min-height:100vh}.content{max-width:1260px;margin:auto;padding:32px}.top{display:flex;justify-content:space-between;align-items:flex-end;gap:14px;margin-bottom:26px}.title{font:600 30px 'Playfair Display',serif}.subtitle{font-size:13px;color:var(--light);margin-top:5px}.buttons{display:flex;gap:7px}.btn{border:1px solid var(--cream-dark);background:var(--warm);padding:9px 13px;cursor:pointer;color:var(--mid);font:500 12px 'DM Sans',sans-serif}.layout{display:grid;grid-template-columns:240px 1fr;gap:18px}.panel,.result{background:var(--warm);border:1px solid var(--cream-dark)}.head{padding:15px 17px;border-bottom:1px solid var(--cream-dark);font-weight:600}.types a{display:block;padding:12px 16px;color:var(--mid);text-decoration:none;border-bottom:1px solid var(--cream-dark)}.types a.active{background:#eef2e9;color:var(--moss);border-left:3px solid var(--moss)}.filter{padding:16px}.group{margin-bottom:12px}.group label{display:block;font-size:9px;text-transform:uppercase;letter-spacing:.8px;color:var(--light);font-weight:700;margin-bottom:6px}.group input,.group select{width:100%;padding:10px;border:1px solid var(--cream-dark);background:white}.filter .btn{width:100%;background:var(--moss);color:white}.result-head{display:flex;justify-content:space-between}.badge{background:var(--cream);color:var(--moss);padding:3px 8px;border-radius:12px;font-size:11px}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%;font-size:12px}th{padding:10px 13px;background:var(--cream);color:var(--light);font-size:9px;text-transform:uppercase;letter-spacing:.8px;text-align:left}td{padding:12px 13px;border-top:1px solid var(--cream-dark);color:var(--mid)}.rating{color:var(--gold);white-space:nowrap}.pill{display:inline-block;padding:4px 8px;border-radius:12px;background:#edf2e8;color:var(--moss);font-size:10px}.pill.pendente{background:#fff1dc;color:#9a651e}.pill.rejeitado,.pill.removido{background:#fae9e7;color:var(--danger)}.empty{text-align:center;padding:55px!important;color:var(--light)}.alert{padding:12px;margin-bottom:15px;background:#fae9e7;color:var(--danger)}#printArea{display:none}@media(max-width:900px){.main{margin-left:0}.layout{grid-template-columns:1fr}.content{padding:20px}.top{align-items:flex-start;flex-direction:column}}@media print{body>*:not(#printArea){display:none!important}#printArea{display:block!important}.print-table{border-collapse:collapse;width:100%;font-size:9px}.print-table td,.print-table th{border:1px solid #bbb;padding:5px}.print-table th{background:#34452a;color:white}.print-title{font:600 20px Georgia;margin-bottom:5px}.print-meta{font-size:10px;margin-bottom:12px}}
</style></head><body><jsp:include page="/pages/includes/sidebar.jsp" /><main class="main"><div class="content"><div class="top"><div><div class="title">Relatórios</div><div class="subtitle"><%="autor".equals(perfil)?"Desempenho das suas receitas e comentários recebidos":"Análises editoriais das receitas e comentários do blog"%></div></div><div class="buttons"><button class="btn" onclick="exportPDF()">⬇ PDF</button><button class="btn" onclick="exportExcel()">⬇ Excel</button><button class="btn" onclick="printReport()">🖨 Imprimir</button></div></div>
<%if(request.getAttribute("erro")!=null){%><div class="alert"><%=h(request.getAttribute("erro"))%></div><%}%>
<div class="layout"><aside><div class="panel"><div class="head">Relatórios</div><nav class="types"><a class="<%="receitas".equals(tipo)?"active":""%>" href="<%=ctx+rota%>?tipo=receitas">📝 Receitas</a><a class="<%="comentarios".equals(tipo)?"active":""%>" href="<%=ctx+rota%>?tipo=comentarios">💬 Comentários &amp; Avaliações</a></nav></div><div class="panel" style="margin-top:14px"><div class="head">Filtros</div><form class="filter" method="get" action="<%=ctx+rota%>"><input type="hidden" name="tipo" value="<%=h(tipo)%>">
<%if("receitas".equals(tipo)){%><div class="group"><label for="categoria">Categoria</label><select id="categoria" name="categoria"><option value="">Todas</option><%for(CategoriaRelatorio c:categorias){%><option value="<%=c.id%>" <%=categoria!=null&&categoria==c.id?"selected":""%>><%=h(c.emoji)%> <%=h(c.nome)%></option><%}%></select></div><%if("editor".equals(perfil)){%><div class="group"><label for="autor">Autor</label><input id="autor" name="autor" value="<%=h(autor)%>" placeholder="Buscar por autor…"></div><%}%><%}else{%><div class="group"><label for="status">Status</label><select id="status" name="status"><option value="">Todos</option><option value="APROVADO" <%="APROVADO".equals(status)?"selected":""%>>Aprovado</option><option value="PENDENTE" <%="PENDENTE".equals(status)?"selected":""%>>Pendente</option><option value="REJEITADO" <%="REJEITADO".equals(status)?"selected":""%>>Rejeitado</option><option value="REMOVIDO" <%="REMOVIDO".equals(status)?"selected":""%>>Removido</option></select></div><div class="group"><label for="dataInicio">Data inicial</label><input type="date" id="dataInicio" name="dataInicio" value="<%=h(di)%>"></div><div class="group"><label for="dataFim">Data final</label><input type="date" id="dataFim" name="dataFim" value="<%=h(df)%>"></div><%}%><button class="btn" type="submit">Gerar visualização</button></form></div></aside>
<section class="result"><div class="head result-head"><span><%="receitas".equals(tipo)?"📝 Receitas — Desempenho":"💬 Últimos Comentários"%></span><span class="badge"><%=total%></span></div><div class="table-wrap"><table id="report-table"><thead><%if("receitas".equals(tipo)){%><tr><th>Receita</th><th>Categoria</th><%if("editor".equals(perfil)){%><th>Autor</th><%}%><th>Visualizações</th><th>Comentários</th><th>Avaliação</th><th>Status</th></tr><%}else{%><tr><th>Usuário</th><th>Receita</th><th>Avaliação</th><th>Data</th><th>Status</th><th>Comentário</th></tr><%}%></thead><tbody>
<%if(total==0){%><tr><td class="empty" colspan="7">Nenhum registro encontrado.</td></tr><%}else if("receitas".equals(tipo)){for(ReceitaRelatorio r:receitas){%><tr><td><strong><%=h(r.titulo)%></strong></td><td><%=h(r.emoji)%> <%=h(r.categoria)%></td><%if("editor".equals(perfil)){%><td><%=h(r.autor)%></td><%}%><td><%=r.visualizacoes%></td><td><%=r.comentarios%></td><td class="rating"><%=String.format(java.util.Locale.US,"%.1f",r.avaliacao)%> ★</td><td><span class="pill <%=h(r.status.toLowerCase())%>"><%=h(label(r.status))%></span></td></tr><%}}else{for(ComentarioRelatorio c:comentarios){%><tr><td><strong><%=h(c.usuario)%></strong></td><td><%=h(c.receita)%></td><td class="rating"><%for(int i=1;i<=5;i++){%><%=i<=c.avaliacao?"★":"☆"%><%}%></td><td><%=h(c.data)%></td><td><span class="pill <%=h(c.status.toLowerCase())%>"><%=h(label(c.status))%></span></td><td><%=h(c.texto)%></td></tr><%}}%>
</tbody></table></div></section></div></div></main><div id="printArea"></div>
<script>
function tableData(){var table=document.getElementById('report-table'),head=Array.from(table.tHead.rows[0].cells).map(function(c){return c.textContent.trim();}),rows=Array.from(table.tBodies[0].rows).filter(function(r){return !r.querySelector('.empty');}).map(function(r){return Array.from(r.cells).map(function(c){return c.textContent.trim();});});return{head:head,rows:rows};}
function requireData(){var d=tableData();if(!d.rows.length){alert('Nenhum registro para exportar.');return null;}return d;}
function exportPDF(){var d=requireData();if(!d)return;var doc=new window.jspdf.jsPDF({orientation:'landscape'});doc.text('Sabor & Arte — Relatórios',14,16);doc.autoTable({head:[d.head],body:d.rows,startY:23,theme:'grid',styles:{fontSize:8},headStyles:{fillColor:[52,69,42]}});doc.save('SaborArte_relatorio_<%=h(tipo)%>_'+Date.now()+'.pdf');}
function exportExcel(){var d=requireData();if(!d)return;var ws=XLSX.utils.aoa_to_sheet([d.head].concat(d.rows)),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Relatório');XLSX.writeFile(wb,'SaborArte_relatorio_<%=h(tipo)%>_'+Date.now()+'.xlsx');}
function printReport(){var d=requireData();if(!d)return;var area=document.getElementById('printArea'),table=document.createElement('table');table.className='print-table';var tr=document.createElement('tr');d.head.forEach(function(x){var th=document.createElement('th');th.textContent=x;tr.appendChild(th);});var thead=document.createElement('thead');thead.appendChild(tr);table.appendChild(thead);var body=document.createElement('tbody');d.rows.forEach(function(row){var r=document.createElement('tr');row.forEach(function(x){var td=document.createElement('td');td.textContent=x;r.appendChild(td);});body.appendChild(r);});table.appendChild(body);area.replaceChildren();var title=document.createElement('div');title.className='print-title';title.textContent='Sabor & Arte — Relatórios';var meta=document.createElement('div');meta.className='print-meta';meta.textContent=new Date().toLocaleString('pt-BR')+' · '+d.rows.length+' registro(s)';area.append(title,meta,table);window.print();}
</script></body></html>
